name: tinder_app_flutter
description: Tinder app made with Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_progress_hud: ^2.0.0
  numberpicker: ^2.1.1
  image_picker: ^0.8.4+11
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_storage: ^10.2.7
  flutter_facebook_auth: ^4.0.1
  cloud_firestore: ^3.1.8
  firebase_messaging: ^11.2.6
  percent_indicator: ^4.0.0
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  intl: ^0.17.0
  csc_picker: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf
        - asset: fonts/Nunito-Bold.ttf

#dependency_overrides:
#  firebase_storage: 10.2.7
#  firebase_core: 1.12.0
#  firebase_auth: 3.3.7
#  cloud_firestore: 3.1.8